/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {


    public static void main(String[] args) {
//        System.out.println("test");
//        Restaurant ress=new Restaurant("haha",7,1);
//        Review revv =new Review("saas","assd",4);
//        System.out.println(ress);
//        System.out.println(revv);

        Restaurant r = new Restaurant("shawerma",2,1);
        Shop s= new Shop("zara","T-shirt",4);
        Theater t =new Theater("petra");
        Movie m1=new Movie("oioi");
        Movie m2=new Movie("oioi");
        Movie m3=new Movie("oioi");
//        System.out.println(r.toString());

//        Review re = new Review("the restaurant is excellent","Mhammad", 5);
//        Review ree = new Review("the restaurant is bad","Khaled", 3);
//        Review reee = new Review("the restaurant is bad","Khaled", 3);
//        System.out.println(re);
        Review shopone=new Review("jojo","lolo",4);
        Review shopTwo=new Review("jo","lolo",3);
        Review shopThree=new Review("hussam","yaseen",2);

        r.addReview("the restaurant is excellent","Mhammad", 5);
        r.addReview("the restaurant is bad","Khaled", 3);
        r.addReview("the restaurant is bad","Khaled", 3);
        System.out.println(r);
        System.out.println("-----------------------------");
        s.addReview("jojo","lolo",1);
        s.addReview("jo","lolo",1);
        s.addReview("joi","lolo",1);
        System.out.println(s);
        System.out.println("-----------------------------");
        t.addFavouritMovies(m1);
        t.addFavouritMovies(m2);
        t.addFavouritMovies(m3);
        t.addReview("rami","kmal",5);
        t.addReview("samer","tala",3);
        t.addReview("jameel","hala",1);
//        t.removeMovie(m);
        System.out.println(t);
    }

}
