/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {


    public static void main(String[] args) {
//        System.out.println("test");
//        Restaurant ress=new Restaurant("haha",7,1);
//        Review revv =new Review("saas","assd",4);
//        System.out.println(ress);
//        System.out.println(revv);

        Restaurant r = new Restaurant("shawerma",2,1);

//        System.out.println(r.toString());

        Review re = new Review("the restaurant is excellent","Mhammad", 5);
        Review ree = new Review("the restaurant is bad","Khaled", 1);
        Review reee = new Review("the restaurant is bad","Sameer", 1);
//        System.out.println(re);

        r.addReview(re);
        r.addReview(ree);
        r.addReview(reee);
        System.out.println(r);

    }

}
