/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
    public Restaurant objOne=new Restaurant("mishmish",2,3);
    @Test public void testForToString(){
                String rest=objOne.toString();
                String expectedOutPut="Restaurant{" +
                        "name='" +"mishmish" + '\'' +
                        ", stars=" + 3 +
                        ", priceCatogery='" + "$$" + '\'' +
                        '}';
                assertEquals(rest,expectedOutPut);
    }
    public Review objReviwe=new Review("kmal","rere",3);
    @Test public void testForToStringForReviwe(){
        String rev=objReviwe.toString();
        String expectedOutPutt="Review{" +
                "body='" + "kmal" + '\'' +
                ", auth='" + "rere" + '\'' +
                ", stars=" +3 +
                '}';
        assertEquals(rev,expectedOutPutt);
    }

}
