import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        pluralize("dog",0);
//        int dogCount = 1;
//        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");
//
//        int catCount = 2;
//        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");
//
//        int turtleCount = 0;
//        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");
//        flipNHeads(5);
        while(true)
//        for (int i =0;i<10;i++) //for test
              {
            LocalDateTime now = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
            String formatDateTime = now.format(formatter);
            System.out.println(formatDateTime);
        }
    }
    public static void pluralize ( String nickName ,int num ){
        if (num ==1 ) {
            System.out.println("I own " +"1"+ "  "+nickName + ".");

        } else {
                    System.out.println("I own " +num+ "  "+nickName + "s .");

        }
    }
    public static void flipNHeads ( int flip ){
        int count =0;
        int headss=0;
        while (headss < flip) {
            double randomDbl = Math.random();
            if (randomDbl >0.5 ) {
                System.out.println("heads" );
                count =count+1;
                headss++;
            } else {
                System.out.println("tail" );
                count =count+1;
                headss=0;
            }
        }
        System.out.println("it took " + count + " flips to flip " + headss + " head in a row");
    }


}
